services:
  frontend:
    image: powerwave-frontend:${APP_VERSION:-local}

    build:
      context: ./frontend

    container_name: powerwave-frontend
    restart: unless-stopped

    ports:
      - "127.0.0.1:8101:80"
  backend:
    image: powerwave-backend:${APP_VERSION:-local}
    build:
      context: ./backend

    container_name: powerwave-backend
    restart: unless-stopped

    user: "1000:1000"

    env_file:
      - .env

    ports:
      - "127.0.0.1:8100:8000"

    volumes:
      - /srv/oruxa/data/powerwave:/data

    networks:
      - oruxa-backend

networks:
  oruxa-backend:
    external: true
