// Event Playback -- Slice 1 (Core Playback Engine) + Slice 2 (speed/seek)
// real-browser coverage. See docs/development/BROWSER_SMOKE_TEST.md for
// the general foundation this extends, and the Playback architecture
// audit / Slice 1 report for why real timer/rAF/Plotly-overlay behavior
// needs a real browser rather than a source-text assertion
// (backend/tests/test_frontend_playback.py covers the structural/static
// invariants that DON'T need one).
//
// Owner product decision (2026-09-12): Playback CONTROLS (Restart/Play/
// Speed/seek) are mounted on Analysis pages only (Phasor today, via
// wwPhasorMountPlaybackControls()) -- the raw Waveform Time Group toolbar
// no longer mounts them (see DECISIONS.md DEC-085's own "Update
// (2026-09-12)" section). This file previously drove every control
// directly from a Waveform Time Group canvas's own `.ww-tg-playback-*`
// elements; it now drives the SAME shared, unchanged engine
// (wwPlayback/wwPlaybackState()/wwPlaybackPlay() etc.) through Phasor's
// own mounted control surface instead -- the engine itself, and every
// invariant these tests guard, is unchanged; only the UI entry point
// used to exercise it changed. The Waveform Time Group canvas's own
// PASSIVE Playback Cursor overlay (`.ww-tg-playback-cursor-overlay`) is
// explicitly preserved (it is a readout of the shared clock, not a
// control) and is still asserted directly against the Waveform canvas
// below.
//
// Fixture: synth_playback(.cfg/.dat) / synth_playback_b(.cfg/.dat) --
// deterministic, committed COMTRADE fixtures generated by
// backend/tests/perf/synthetic_comtrade.py (the SAME generator the F2
// performance baseline uses), 3 analog (V0_R/V0_Y/V0_B) + 4 digital
// channels, 50 Hz, a DELIBERATELY long-for-a-test-fixture 4-second
// duration -- long enough that "wait a short real interval, assert
// playback advanced but has not yet completed" is reliable, unlike the
// pre-existing ~10-40ms smoke-test fixtures. `synth_playback_b` carries a
// different (non-overlapping) recording start date so it forms its own,
// SEPARATE Time Group from `synth_playback` when both are loaded into one
// workspace.
//
// Assertions stay at the "did it move / did it stop / did it respond"
// level throughout (no exact frame-count or pixel-delta assertions,
// matching the existing smoke test's own established philosophy) --
// timing-sensitive real-browser behavior is inherently non-deterministic
// down to the millisecond.

const { test, expect } = require("@playwright/test");
const path = require("path");

const FIXTURES = path.join(__dirname, "..", "backend", "tests", "fixtures", "comtrade");
const BACKEND_URL = `http://127.0.0.1:${process.env.PW_BACKEND_PORT || "8000"}`;

async function uploadFixture(page, stem) {
  await page.goto("/index.html");
  await page.locator("#recordingsUploadBtn, #recordingsEmptyUploadBtn").first().click();
  await expect(page.locator("#uploadModalOverlay")).toBeVisible();
  await page.locator("#uploadModalFile_0").setInputFiles(path.join(FIXTURES, `${stem}.cfg`));
  await page.locator("#uploadModalFile_1").setInputFiles(path.join(FIXTURES, `${stem}.dat`));
  await page.locator("#uploadModalSubmitBtn").click();
  await page.locator("#uploadModalOverlay").waitFor({ state: "hidden" });
}

// Displays a given source's first analog channel on the Waveform page --
// this is what actually forms a real Time Group (a Playback/Phasor
// concept driven entirely off DISPLAYED channels, never upload alone).
// Assumes the Recordings page is already showing `sourceId`'s own row.
async function displayFirstAnalogChannel(page, sourceId) {
  await page.locator(`#recordingsTableBody tr[data-source-id="${sourceId}"]`).click();
  await expect(page.locator("#wwWorkspaceLoading")).toBeHidden();
  const details = page.locator(`#channelGroups details.source-recording[data-source-id="${sourceId}"]`);
  await expect(details).toBeVisible();
  if (!(await details.evaluate((el) => el.open))) await details.locator("> summary").click();
  const channelRow = page
    .locator(`#channelGroups tr.channel-row--toggle[data-channel-kind="analog"][data-source-id="${sourceId}"]`)
    .first();
  await expect(channelRow).toBeVisible();
  await channelRow.click();
  await expect(channelRow).toHaveAttribute("aria-pressed", "true");
  await expect(page.locator(".ww-chart .plotly").first()).toBeVisible();
}

// A minimal, single-member Engineering Context (Va only, from the
// fixture's own bare-role `V0_R` channel) -- Playback-engine coverage
// doesn't need a full six-role bay, just ONE resolvable role so Phasor
// can claim the source's own Time Group and mount real Playback controls
// against it (a partial bay is a normal, fully-supported result -- see
// PHASOR_ANALYSIS.md).
async function createSinglePhaseContext(page, workspaceId, sourceId, displayName) {
  const response = await page.request.post(
    `${BACKEND_URL}/api/v1/workspaces/${encodeURIComponent(workspaceId)}/engineering-contexts`,
    {
      data: {
        display_name: displayName,
        status: "manual",
        members: [
          {
            channel_ref: { kind: "source", source_id: sourceId, channel_name: "V0_R" },
            phase: "A",
            phase_source: "engineer_confirmed",
          },
        ],
      },
    }
  );
  expect(response.ok()).toBeTruthy();
  return response.json();
}

// Full setup: upload a fixture, display its first channel (forms the real
// Time Group and gives access to the Waveform canvas's own passive
// Playback Cursor overlay), create a single-phase Engineering Context
// against it, then open Analysis -> Phasor and select that context so its
// own Playback ribbon mounts. Returns the Waveform canvas locator (for
// `.ww-tg-playback-cursor-overlay` assertions) and the Phasor Playback
// mount locator (for the actual Restart/Play/Speed/seek controls).
async function setupPhasorPlayback(page, stem, displayName) {
  await uploadFixture(page, stem);
  const row = page.locator("#recordingsTableBody tr[data-source-id]").last();
  await expect(row).toBeVisible();
  const sourceId = await row.getAttribute("data-source-id");
  const workspaceId = await page.evaluate(() => localStorage.getItem("powerwave.workspaceId"));

  await displayFirstAnalogChannel(page, sourceId);
  const canvas = page.locator("#wwTimeGroupCanvases .ww-time-group-canvas").first();
  await expect(canvas).toBeVisible();
  // Playback controls are Analysis-only now -- confirm the removal
  // invariant holds for every caller of this setup, not just a dedicated
  // test (belt-and-braces; the dedicated test below is still the primary
  // documentation of this invariant).
  await expect(canvas.locator(".ww-tg-playback-play-btn")).toHaveCount(0);

  const context = await createSinglePhaseContext(page, workspaceId, sourceId, displayName);

  await page.locator("#mainNavAnalysisBtn").click();
  await expect(page.locator("#pageAnalysis")).toBeVisible();
  await expect(page.locator(`#wwPhasorContextSelect option[value="${context.id}"]`)).toHaveCount(1);
  await page.locator("#wwPhasorContextSelect").selectOption(context.id);

  const mount = page.locator("#wwPhasorPlaybackMount");
  await expect(mount.locator(".ww-tg-playback-play-btn")).toBeVisible();

  return { canvas, mount, sourceId, workspaceId, contextId: context.id };
}

test.describe("Event Playback Slice 1", () => {
  test("Waveform Time Group toolbar no longer mounts Playback controls", async ({ page }) => {
    await uploadFixture(page, "synth_playback");
    const row = page.locator("#recordingsTableBody tr[data-source-id]").last();
    const sourceId = await row.getAttribute("data-source-id");
    await displayFirstAnalogChannel(page, sourceId);

    const canvas = page.locator("#wwTimeGroupCanvases .ww-time-group-canvas").first();
    await expect(canvas).toBeVisible();
    await expect(canvas.locator(".ww-tg-playback-play-btn")).toHaveCount(0);
    await expect(canvas.locator(".ww-tg-playback-restart-btn")).toHaveCount(0);
    await expect(canvas.locator(".ww-tg-playback-speed-select")).toHaveCount(0);
    await expect(canvas.locator(".ww-tg-playback-seek-slider")).toHaveCount(0);
    // The passive Playback Cursor overlay (not a control) is preserved.
    await expect(canvas.locator(".ww-tg-playback-cursor-overlay")).toHaveCount(1);
    // Everything else on the toolbar is unaffected.
    await expect(canvas.locator(".ww-tg-reset-view-btn")).toBeVisible();
    await expect(canvas.locator(".ww-tg-autoscale-btn")).toBeVisible();
    await expect(canvas.locator(".ww-tg-cursor-mode-btn")).toBeVisible();
  });

  // ---- Test 1: Play moves ----
  test("Play advances the current-time readout and shows the playback cursor", async ({ page }) => {
    const { canvas, mount } = await setupPhasorPlayback(page, "synth_playback", "Alpha");
    const playBtn = mount.locator(".ww-tg-playback-play-btn");
    const readout = mount.locator(".ww-tg-playback-time-readout");

    const before = await readout.textContent();
    await playBtn.click();
    await expect(playBtn).toHaveText("Pause");

    // A real wall-clock wait -- not an exact frame count (per this
    // slice's own "wall-clock anchor, never assumed frame interval"
    // timing design, this is the only meaningful way to observe motion).
    await page.waitForTimeout(500);

    const after = await readout.textContent();
    expect(after).not.toBe(before);

    // The dedicated Playback Cursor overlay lives on the WAVEFORM canvas
    // (a passive readout of the shared clock, not a control) -- it only
    // actually renders while the Waveform page itself is the visible one
    // (wwUpdatePlaybackCursorOverlay()'s own `document.getElementById(
    // "viewWaveform")`/ruler-visibility gate), so this navigates there to
    // observe it, exactly like a real engineer switching from Analysis
    // back to Waveform mid-playback would.
    await page.locator("#mainNavWaveformBtn").click();
    await expect(canvas.locator(".ww-tg-playback-cursor-overlay")).toBeVisible();
  });

  // ---- Test 2: Pause stops ----
  test("Pause freezes the current-time readout", async ({ page }) => {
    const { mount } = await setupPhasorPlayback(page, "synth_playback", "Alpha");
    const playBtn = mount.locator(".ww-tg-playback-play-btn");
    const readout = mount.locator(".ww-tg-playback-time-readout");

    await playBtn.click();
    await page.waitForTimeout(400);
    await playBtn.click(); // Pause
    await expect(playBtn).toHaveText("Play");

    const frozen = await readout.textContent();
    await page.waitForTimeout(400);
    const stillFrozen = await readout.textContent();
    expect(stillFrozen).toBe(frozen);
  });

  // ---- Test 3: Restart ----
  test("Restart returns playback to the Time Group's own range start", async ({ page }) => {
    const { mount } = await setupPhasorPlayback(page, "synth_playback", "Alpha");
    const playBtn = mount.locator(".ww-tg-playback-play-btn");
    const restartBtn = mount.locator(".ww-tg-playback-restart-btn");
    const readout = mount.locator(".ww-tg-playback-time-readout");

    await playBtn.click();
    await page.waitForTimeout(500);
    const advanced = await readout.textContent();

    await restartBtn.click();
    await expect(playBtn).toHaveText("Play"); // Restart lands in "stopped", not "playing"
    const restarted = await readout.textContent();
    expect(restarted).not.toBe(advanced);

    // Pressing Play again after Restart must resume from the START, not
    // from wherever it was before -- confirmed indirectly: the readout
    // right after Restart must exactly match the readout captured right
    // after Restart a second time (idempotent "jump to start"), and must
    // differ from the mid-playback value captured above.
    await restartBtn.click();
    const restartedAgain = await readout.textContent();
    expect(restartedAgain).toBe(restarted);
  });

  // ---- Test 4: only one active Time Group plays at a time ----
  // Owner decision (DEC-085): ONE Playback Controller, ONE active Time
  // Group at a time -- an engine invariant, not a UI one. With Playback
  // controls now Analysis-only (a single mount, following whichever
  // context is selected), this exercises the invariant directly through
  // the same public consumer seam (wwPlaybackPlay()/wwPlaybackState())
  // this whole file already reads state through, against TWO real,
  // independently-displayed Time Groups.
  test("Playing a second Time Group stops the first", async ({ page }) => {
    // Two independent fixtures with non-overlapping recording start
    // times -- see this file's own header comment -- so they resolve to
    // TWO separate Time Groups (never merged) once both are displayed in
    // the same workspace.
    await uploadFixture(page, "synth_playback");
    await uploadFixture(page, "synth_playback_b");

    const rows = page.locator("#recordingsTableBody tr[data-source-id]");
    await expect(rows).toHaveCount(2);
    const sourceIdA = await rows.nth(0).getAttribute("data-source-id");
    const sourceIdB = await rows.nth(1).getAttribute("data-source-id");

    for (const sourceId of [sourceIdA, sourceIdB]) {
      await page.locator("#mainNavRecordingsBtn").click();
      await displayFirstAnalogChannel(page, sourceId);
    }

    const canvases = page.locator("#wwTimeGroupCanvases .ww-time-group-canvas");
    await expect(canvases).toHaveCount(2);

    const groupIdA = await page.evaluate((sid) => wwTimeGroupIdForDisplaySourceId(sid), sourceIdA);
    const groupIdB = await page.evaluate((sid) => wwTimeGroupIdForDisplaySourceId(sid), sourceIdB);
    expect(groupIdA).not.toBe(groupIdB);
    // Selected by `data-time-group-id`, never DOM position -- Time Group
    // canvases are not guaranteed to render in upload/display order.
    const canvasA = page.locator(`#wwTimeGroupCanvases .ww-time-group-canvas[data-time-group-id="${groupIdA}"]`);

    await page.evaluate((gid) => wwPlaybackPlay(gid), groupIdA);
    await expect.poll(() => page.evaluate(() => wwPlaybackState().state)).toBe("playing");
    expect(await page.evaluate(() => wwPlaybackState().activeTimeGroupId)).toBe(groupIdA);

    await page.evaluate((gid) => wwPlaybackPlay(gid), groupIdB);
    await expect.poll(() => page.evaluate(() => wwPlaybackState().activeTimeGroupId)).toBe(groupIdB);
    expect(await page.evaluate(() => wwPlaybackState().state)).toBe("playing");
    // Group A must have stopped -- ONE Playback Controller, one active
    // group at a time (never two simultaneous animation loops); its own
    // passive cursor overlay is hidden again.
    await expect(canvasA.locator(".ww-tg-playback-cursor-overlay")).toBeHidden();
  });

  // ---- Test 5: workspace reset while playing ----
  test("Clearing the workspace while playing stops Playback with no stale errors", async ({ page }) => {
    const consoleErrors = [];
    page.on("console", (msg) => {
      if (msg.type() === "error") consoleErrors.push(msg.text());
    });
    page.on("pageerror", (err) => consoleErrors.push(`pageerror: ${err.message}`));

    const { mount } = await setupPhasorPlayback(page, "synth_playback", "Alpha");
    const playBtn = mount.locator(".ww-tg-playback-play-btn");
    await playBtn.click();
    await expect(playBtn).toHaveText("Pause");
    await page.waitForTimeout(300);

    // "Start new workspace" lives on the Recordings page (Phase 3B-UAT2:
    // relocated there as the one workspace-management surface).
    await page.locator("#mainNavRecordingsBtn").click();
    await expect(page.locator("#newWorkspaceButton")).toBeVisible();
    await page.locator("#newWorkspaceButton").click();
    await expect(page.locator("#newWorkspaceConfirmOverlay")).toBeVisible();
    await page.locator("#newWorkspaceConfirmStartBtn").click();
    await expect(page.locator("#newWorkspaceConfirmOverlay")).toBeHidden();

    // The workspace is now empty -- no Time Group canvas, so nothing left
    // for a stale rAF loop to draw into. Give any (there should be none)
    // still-scheduled animation frame a chance to fire and throw before
    // asserting a clean console.
    await page.waitForTimeout(300);
    await expect(page.locator("#wwTimeGroupCanvases .ww-time-group-canvas")).toHaveCount(0);
    expect(consoleErrors, `Unexpected console/page errors:\n${consoleErrors.join("\n")}`).toEqual([]);
  });
});

// ---- Slice 2: Essential Playback Controls (speed + seek) ----
//
// Numeric comparisons read wwPlaybackState().currentTime directly (the
// Slice 1 consumer seam) rather than parsing the formatted readout text
// -- reliable, and exactly the public surface a future consumer would
// read too. The seek scrubber is driven via a direct `.value` write +
// dispatched `input`/`change` events (the standard, non-flaky way to
// drive an `<input type="range">` in a real browser test -- a literal
// pixel-accurate mouse drag would be far more brittle for no extra
// coverage) rather than a mouse drag; this still exercises the REAL
// event listeners exactly as a native drag/keyboard interaction would.
async function seekTo(slider, value, { commit = true } = {}) {
  await slider.evaluate(
    (el, args) => {
      el.value = String(args.value);
      el.dispatchEvent(new Event("input", { bubbles: true }));
      if (args.commit) el.dispatchEvent(new Event("change", { bubbles: true }));
    },
    { value, commit }
  );
}

async function seekSliderBounds(slider) {
  return slider.evaluate((el) => ({ min: parseFloat(el.min), max: parseFloat(el.max) }));
}

test.describe("Event Playback Slice 2", () => {
  test("2x speed advances materially farther than 1x over the same real interval", async ({ page }) => {
    const { mount } = await setupPhasorPlayback(page, "synth_playback", "Alpha");
    const playBtn = mount.locator(".ww-tg-playback-play-btn");
    const restartBtn = mount.locator(".ww-tg-playback-restart-btn");
    const speedSelect = mount.locator(".ww-tg-playback-speed-select");

    // ---- 1x baseline ----
    await restartBtn.click();
    await expect(speedSelect).toHaveValue("1"); // default, unaffected by Restart
    await playBtn.click();
    await page.waitForTimeout(500);
    const startTime = await page.evaluate(() => wwPlaybackState().startTime);
    const delta1x = (await page.evaluate(() => wwPlaybackState().currentTime)) - startTime;
    await playBtn.click(); // pause

    // ---- restart, switch to 2x, play the SAME real interval ----
    await restartBtn.click();
    await speedSelect.selectOption("2");
    await expect(speedSelect).toHaveValue("2");
    await playBtn.click();
    await page.waitForTimeout(500);
    const delta2x = (await page.evaluate(() => wwPlaybackState().currentTime)) - startTime;

    // Materially farther, never an exact 2.0x ratio assertion (real
    // wall-clock timing jitter) -- 1.3x is a generous, non-flaky margin
    // comfortably below the ~2x expected while still proving a real
    // difference.
    expect(delta2x).toBeGreaterThan(delta1x * 1.3);
  });

  test("0.05x and 0.10x speeds support Play/Pause/Seek/Restart like any other speed", async ({ page }) => {
    // Extended minimum speeds (owner instruction, 2026-09-12) for slow
    // engineering-event inspection -- e.g. watching a Phasor fault
    // transition unfold. Real-time waits below stay short since these
    // are the SLOWEST speeds (least simulated-time movement per real
    // second); the point is that Play/Pause/Seek/Restart all still work
    // correctly at these values, not a speed-ratio comparison.
    const { mount } = await setupPhasorPlayback(page, "synth_playback", "Alpha");
    const playBtn = mount.locator(".ww-tg-playback-play-btn");
    const restartBtn = mount.locator(".ww-tg-playback-restart-btn");
    const speedSelect = mount.locator(".ww-tg-playback-speed-select");
    const slider = mount.locator(".ww-tg-playback-seek-slider");

    // ---- Play/Pause at 0.05x ----
    await speedSelect.selectOption("0.05");
    await expect(speedSelect).toHaveValue("0.05");
    await restartBtn.click();
    await expect(speedSelect).toHaveValue("0.05"); // Restart never resets speed
    const startTime = await page.evaluate(() => wwPlaybackState().startTime);

    await playBtn.click();
    await expect(playBtn).toHaveText("Pause");
    await page.waitForTimeout(300);
    const delta005 = (await page.evaluate(() => wwPlaybackState().currentTime)) - startTime;
    expect(delta005).toBeGreaterThan(0); // clock is genuinely advancing
    expect(delta005).toBeLessThan(0.1); // and only by a tiny, 0.05x-consistent amount

    await playBtn.click(); // pause
    await expect(playBtn).toHaveText("Play");
    const pausedAt005 = await page.evaluate(() => wwPlaybackState().currentTime);
    await page.waitForTimeout(150);
    // Clock genuinely stopped -- no drift while paused.
    expect(await page.evaluate(() => wwPlaybackState().currentTime)).toBe(pausedAt005);

    // ---- Play/Pause at 0.10x (materially faster than 0.05x, still slow) ----
    await restartBtn.click();
    await speedSelect.selectOption("0.1");
    await expect(speedSelect).toHaveValue("0.1");
    await playBtn.click();
    await page.waitForTimeout(300);
    const delta01 = (await page.evaluate(() => wwPlaybackState().currentTime)) - startTime;
    expect(delta01).toBeGreaterThan(delta005 * 1.3); // ~2x 0.05x's rate, generous non-flaky margin
    await playBtn.click(); // pause

    // ---- Seek while at 0.10x ----
    const { min, max } = await seekSliderBounds(slider);
    const target = min + (max - min) * 0.5;
    await seekTo(slider, target);
    const afterSeek = await page.evaluate(() => wwPlaybackState().currentTime);
    expect(Math.abs(afterSeek - target)).toBeLessThan(0.01);
    await expect(speedSelect).toHaveValue("0.1"); // seek never resets speed

    // ---- Restart at 0.10x lands honestly back at start ----
    await restartBtn.click();
    const currentTime = await page.evaluate(() => wwPlaybackState().currentTime);
    expect(currentTime).toBe(startTime);
    await expect(speedSelect).toHaveValue("0.1"); // Restart never resets speed
  });

  test("Speed selection is shared across Analysis and Waveform re-visits (one controller-wide value)", async ({ page }) => {
    // One Playback Controller, one speed -- never a per-group setting
    // (DEC-085/Slice 2's own architecture). Changing it on the ONE
    // mounted Analysis control surface, then navigating away and back,
    // must still reflect that same shared value (a fresh mount syncs to
    // wwPlayback's CURRENT value, per wwWirePlaybackControls()'s own
    // documented behavior) -- proving the value truly lives on the
    // shared controller, not on the control's own local DOM state.
    const { mount } = await setupPhasorPlayback(page, "synth_playback", "Alpha");
    await mount.locator(".ww-tg-playback-speed-select").selectOption("4");
    await expect(mount.locator(".ww-tg-playback-speed-select")).toHaveValue("4");
    expect(await page.evaluate(() => wwPlaybackState().speed)).toBe(4);

    await page.locator("#mainNavRecordingsBtn").click();
    await page.locator("#mainNavAnalysisBtn").click();
    await expect(page.locator("#wwPhasorPlaybackMount .ww-tg-playback-speed-select")).toHaveValue("4");
  });

  test("Seek moves the readout/cursor substantially and playback continues from there", async ({ page }) => {
    const { canvas, mount } = await setupPhasorPlayback(page, "synth_playback", "Alpha");
    const playBtn = mount.locator(".ww-tg-playback-play-btn");
    const readout = mount.locator(".ww-tg-playback-time-readout");
    const slider = mount.locator(".ww-tg-playback-seek-slider");

    const beforeReadout = await readout.textContent();
    const { min, max } = await seekSliderBounds(slider);
    const target = min + (max - min) * 0.75;

    await seekTo(slider, target);

    const afterReadout = await readout.textContent();
    expect(afterReadout).not.toBe(beforeReadout);
    const currentTime = await page.evaluate(() => wwPlaybackState().currentTime);
    expect(Math.abs(currentTime - target)).toBeLessThan(0.01);

    // Playback can continue from the new (sought) position.
    await playBtn.click();
    await page.waitForTimeout(400);
    const afterPlayTime = await page.evaluate(() => wwPlaybackState().currentTime);
    expect(afterPlayTime).toBeGreaterThan(target);

    // The dedicated Playback Cursor overlay lives on the WAVEFORM canvas
    // (a passive readout, not a control) -- only renders while that page
    // is the visible one, so confirm it there.
    await page.locator("#mainNavWaveformBtn").click();
    await expect(canvas.locator(".ww-tg-playback-cursor-overlay")).toBeVisible();
  });

  test("Seek while stopped lands in paused, not playing", async ({ page }) => {
    const { mount } = await setupPhasorPlayback(page, "synth_playback", "Alpha");
    const playBtn = mount.locator(".ww-tg-playback-play-btn");
    const slider = mount.locator(".ww-tg-playback-seek-slider");
    const { min, max } = await seekSliderBounds(slider);

    await seekTo(slider, min + (max - min) * 0.4);

    await expect(playBtn).toHaveText("Play"); // not auto-playing
    const state = await page.evaluate(() => wwPlaybackState().state);
    expect(state).toBe("paused");
  });

  test("Seeking while playing suspends the clock mid-drag, then resumes automatically on commit", async ({ page }) => {
    const { mount } = await setupPhasorPlayback(page, "synth_playback", "Alpha");
    const playBtn = mount.locator(".ww-tg-playback-play-btn");
    const slider = mount.locator(".ww-tg-playback-seek-slider");
    const { min, max } = await seekSliderBounds(slider);
    const target = min + (max - min) * 0.6;

    await playBtn.click();
    await page.waitForTimeout(200);

    // Mid-drag (input only, no change yet) -- currentTime tracks the
    // drag position exactly (visual-only interpolation, no fabricated
    // engineering data), the clock does not fight it.
    await seekTo(slider, target, { commit: false });
    const midDragTime = await page.evaluate(() => wwPlaybackState().currentTime);
    expect(Math.abs(midDragTime - target)).toBeLessThan(0.01);

    // Commit (change event) -- resumes playing automatically from here.
    await slider.evaluate((el) => el.dispatchEvent(new Event("change", { bubbles: true })));
    await expect(playBtn).toHaveText("Pause");
    await page.waitForTimeout(300);
    const afterResumeTime = await page.evaluate(() => wwPlaybackState().currentTime);
    expect(afterResumeTime).toBeGreaterThan(target);
  });

  test("Pause, seek, then Play resumes from the sought position, not the old one", async ({ page }) => {
    const { mount } = await setupPhasorPlayback(page, "synth_playback", "Alpha");
    const playBtn = mount.locator(".ww-tg-playback-play-btn");
    const slider = mount.locator(".ww-tg-playback-seek-slider");

    await playBtn.click();
    await page.waitForTimeout(300);
    await playBtn.click(); // pause
    const pausedAt = await page.evaluate(() => wwPlaybackState().currentTime);

    const { min, max } = await seekSliderBounds(slider);
    const target = min + (max - min) * 0.9; // far forward, away from pausedAt
    await seekTo(slider, target);
    await expect(playBtn).toHaveText("Play"); // remains paused, not auto-resumed

    await playBtn.click(); // resume
    await expect(playBtn).toHaveText("Pause");
    await page.waitForTimeout(200);
    const afterResume = await page.evaluate(() => wwPlaybackState().currentTime);

    expect(afterResume).toBeGreaterThan(target - 0.05);
    // Clearly resumed from the SOUGHT position, not the old paused one.
    expect(afterResume).toBeGreaterThan(pausedAt + (target - pausedAt) * 0.5);
  });

  test("Restart returns the seek slider and cursor to the range start", async ({ page }) => {
    const { mount } = await setupPhasorPlayback(page, "synth_playback", "Alpha");
    const playBtn = mount.locator(".ww-tg-playback-play-btn");
    const restartBtn = mount.locator(".ww-tg-playback-restart-btn");
    const slider = mount.locator(".ww-tg-playback-seek-slider");

    await playBtn.click();
    await page.waitForTimeout(400);
    await restartBtn.click();

    const startTime = await page.evaluate(() => wwPlaybackState().startTime);
    const currentTime = await page.evaluate(() => wwPlaybackState().currentTime);
    expect(currentTime).toBe(startTime);
    const sliderValue = await slider.evaluate((el) => parseFloat(el.value));
    expect(Math.abs(sliderValue - startTime)).toBeLessThan(0.01);
  });
});
