// Event Playback -- Slice 1 (Core Playback Engine) real-browser coverage.
// See docs/development/BROWSER_SMOKE_TEST.md for the general foundation
// this extends, and the Playback architecture audit / Slice 1 report for
// why real timer/rAF/Plotly-overlay behavior needs a real browser rather
// than a source-text assertion (backend/tests/test_frontend_playback.py
// covers the structural/static invariants that DON'T need one).
//
// Fixture: synth_playback(.cfg/.dat) / synth_playback_b(.cfg/.dat) --
// deterministic, committed COMTRADE fixtures generated by
// backend/tests/perf/synthetic_comtrade.py (the SAME generator the F2
// performance baseline uses), 3 analog + 4 digital channels, 50 Hz, a
// DELIBERATELY long-for-a-test-fixture 4-second duration -- long enough
// that "wait a short real interval, assert playback advanced but has not
// yet completed" is reliable, unlike the pre-existing ~10-40ms smoke-test
// fixtures. `synth_playback_b` carries a different (non-overlapping)
// recording start date so it forms its own, SEPARATE Time Group from
// `synth_playback` when both are loaded into one workspace (Test 4).
//
// Assertions stay at the "did it move / did it stop / did it respond"
// level throughout (no exact frame-count or pixel-delta assertions,
// matching the existing smoke test's own established philosophy) --
// timing-sensitive real-browser behavior is inherently non-deterministic
// down to the millisecond.

const { test, expect } = require("@playwright/test");
const path = require("path");

const FIXTURES = path.join(__dirname, "..", "backend", "tests", "fixtures", "comtrade");

async function uploadFixture(page, stem) {
  await page.goto("/index.html");
  await page.locator("#recordingsUploadBtn, #recordingsEmptyUploadBtn").first().click();
  await expect(page.locator("#uploadModalOverlay")).toBeVisible();
  await page.locator("#uploadModalFile_0").setInputFiles(path.join(FIXTURES, `${stem}.cfg`));
  await page.locator("#uploadModalFile_1").setInputFiles(path.join(FIXTURES, `${stem}.dat`));
  await page.locator("#uploadModalSubmitBtn").click();
  await page.locator("#uploadModalOverlay").waitFor({ state: "hidden" });
}

// Uploads ONE fixture and displays its first analog channel -- the common
// setup every test below needs. Returns the Time Group canvas locator.
async function uploadAndDisplayFirstChannel(page, stem) {
  await uploadFixture(page, stem);
  const row = page.locator("#recordingsTableBody tr[data-source-id]").last();
  await expect(row).toBeVisible();
  await row.click();
  // selectSource() shows #wwWorkspaceLoading synchronously and clears it
  // in a `finally` once its own (multi-step, awaited) fetch chain fully
  // settles -- waiting for it to hide is the robust signal that the
  // sidebar has finished (re)building, rather than racing an arbitrary
  // timeout against that async work.
  await expect(page.locator("#wwWorkspaceLoading")).toBeHidden();
  const channelRow = page.locator('#channelGroups tr.channel-row--toggle[data-channel-kind="analog"]').first();
  await expect(channelRow).toBeVisible();
  await channelRow.click();
  await expect(channelRow).toHaveAttribute("aria-pressed", "true");
  await expect(page.locator(".ww-chart .plotly").first()).toBeVisible();

  const canvas = page.locator("#wwTimeGroupCanvases .ww-time-group-canvas").first();
  await expect(canvas).toBeVisible();
  await expect(canvas.locator(".ww-tg-playback-play-btn")).toBeVisible();
  return canvas;
}

test.describe("Event Playback Slice 1", () => {
  // ---- Test 1: Play moves ----
  test("Play advances the current-time readout and shows the playback cursor", async ({ page }) => {
    const canvas = await uploadAndDisplayFirstChannel(page, "synth_playback");
    const playBtn = canvas.locator(".ww-tg-playback-play-btn");
    const readout = canvas.locator(".ww-tg-playback-time-readout");

    const before = await readout.textContent();
    await playBtn.click();
    await expect(playBtn).toHaveText("Pause");

    // A real wall-clock wait -- not an exact frame count (per this
    // slice's own "wall-clock anchor, never assumed frame interval"
    // timing design, this is the only meaningful way to observe motion).
    await page.waitForTimeout(500);

    const after = await readout.textContent();
    expect(after).not.toBe(before);
    // The dedicated Playback Cursor overlay (NOT Cursor A/B) is now drawn.
    await expect(canvas.locator(".ww-tg-playback-cursor-overlay")).toBeVisible();
  });

  // ---- Test 2: Pause stops ----
  test("Pause freezes the current-time readout", async ({ page }) => {
    const canvas = await uploadAndDisplayFirstChannel(page, "synth_playback");
    const playBtn = canvas.locator(".ww-tg-playback-play-btn");
    const readout = canvas.locator(".ww-tg-playback-time-readout");

    await playBtn.click();
    await page.waitForTimeout(400);
    await playBtn.click(); // Pause
    await expect(playBtn).toHaveText("Play");

    const frozen = await readout.textContent();
    await page.waitForTimeout(400);
    const stillFrozen = await readout.textContent();
    expect(stillFrozen).toBe(frozen);
  });

  // ---- Test 3: Restart ----
  test("Restart returns playback to the Time Group's own range start", async ({ page }) => {
    const canvas = await uploadAndDisplayFirstChannel(page, "synth_playback");
    const playBtn = canvas.locator(".ww-tg-playback-play-btn");
    const restartBtn = canvas.locator(".ww-tg-playback-restart-btn");
    const readout = canvas.locator(".ww-tg-playback-time-readout");

    await playBtn.click();
    await page.waitForTimeout(500);
    const advanced = await readout.textContent();

    await restartBtn.click();
    await expect(playBtn).toHaveText("Play"); // Restart lands in "stopped", not "playing"
    const restarted = await readout.textContent();
    expect(restarted).not.toBe(advanced);

    // Pressing Play again after Restart must resume from the START, not
    // from wherever it was before -- confirmed indirectly: the readout
    // right after Restart must exactly match the readout captured right
    // after Restart a second time (idempotent "jump to start"), and must
    // differ from the mid-playback value captured above.
    await restartBtn.click();
    const restartedAgain = await readout.textContent();
    expect(restartedAgain).toBe(restarted);
  });

  // ---- Test 4: only one active Time Group plays at a time ----
  test("Playing a second Time Group stops the first", async ({ page }) => {
    // Two independent fixtures with non-overlapping recording start
    // times -- see this file's own header comment -- so they resolve to
    // TWO separate Time Groups (never merged) once both are displayed in
    // the same workspace.
    await uploadFixture(page, "synth_playback");
    await uploadFixture(page, "synth_playback_b");

    const rows = page.locator("#recordingsTableBody tr[data-source-id]");
    await expect(rows).toHaveCount(2);
    const sourceIdA = await rows.nth(0).getAttribute("data-source-id");
    const sourceIdB = await rows.nth(1).getAttribute("data-source-id");

    // Scoped by data-source-id (not `.first()`) -- selectSource() rebuilds
    // the WHOLE multi-source sidebar on every call (refreshSourceList()
    // re-fetches every uploaded source's own channels, not just the
    // clicked one), so both sources' rows can be present at once; each
    // iteration below waits for its OWN chart to render before moving to
    // the next source, so the second selectSource() call never races the
    // first one's own still-in-flight fetch chain. Opening a recording
    // (openRecordingForAnalysis()) navigates to the Waveform page, hiding
    // #pageRecordings/#recordingsTableBody -- back to Recordings before
    // every row click, exactly like a real user would.
    for (const sourceId of [sourceIdA, sourceIdB]) {
      await page.locator("#mainNavRecordingsBtn").click();
      await page.locator(`#recordingsTableBody tr[data-source-id="${sourceId}"]`).click();
      await expect(page.locator("#wwWorkspaceLoading")).toBeHidden();
      // Only the FIRST source's own `<details class="source-recording">`
      // opens by default (isFirst, see wwRenderSourceRecordingHtml()) --
      // every later source renders collapsed, exactly like a real user
      // would need to expand it themselves.
      const details = page.locator(`#channelGroups details.source-recording[data-source-id="${sourceId}"]`);
      await expect(details).toBeVisible();
      if (!(await details.evaluate((el) => el.open))) {
        await details.locator("> summary").click();
      }
      const channelRow = page
        .locator(`#channelGroups tr.channel-row--toggle[data-channel-kind="analog"][data-source-id="${sourceId}"]`)
        .first();
      await expect(channelRow).toBeVisible();
      await channelRow.click();
      await expect(channelRow).toHaveAttribute("aria-pressed", "true");
      await expect(page.locator(".ww-chart .plotly").first()).toBeVisible();
    }

    const canvases = page.locator("#wwTimeGroupCanvases .ww-time-group-canvas");
    await expect(canvases).toHaveCount(2);
    const canvasA = canvases.nth(0);
    const canvasB = canvases.nth(1);
    const playA = canvasA.locator(".ww-tg-playback-play-btn");
    const playB = canvasB.locator(".ww-tg-playback-play-btn");

    await playA.click();
    await expect(playA).toHaveText("Pause");

    await playB.click();
    await expect(playB).toHaveText("Pause");
    // Group A must have stopped -- ONE Playback Controller, one active
    // group at a time (never two simultaneous animation loops).
    await expect(playA).toHaveText("Play");
    await expect(canvasA.locator(".ww-tg-playback-cursor-overlay")).toBeHidden();
  });

  // ---- Test 5: workspace reset while playing ----
  test("Clearing the workspace while playing stops Playback with no stale errors", async ({ page }) => {
    const consoleErrors = [];
    page.on("console", (msg) => {
      if (msg.type() === "error") consoleErrors.push(msg.text());
    });
    page.on("pageerror", (err) => consoleErrors.push(`pageerror: ${err.message}`));

    const canvas = await uploadAndDisplayFirstChannel(page, "synth_playback");
    const playBtn = canvas.locator(".ww-tg-playback-play-btn");
    await playBtn.click();
    await expect(playBtn).toHaveText("Pause");
    await page.waitForTimeout(300);

    // "Start new workspace" lives on the Recordings page (Phase 3B-UAT2:
    // relocated there as the one workspace-management surface) -- not on
    // the Waveform page this test has been on since uploadAndDisplayFirstChannel().
    await page.locator("#mainNavRecordingsBtn").click();
    await expect(page.locator("#newWorkspaceButton")).toBeVisible();
    await page.locator("#newWorkspaceButton").click();
    await expect(page.locator("#newWorkspaceConfirmOverlay")).toBeVisible();
    await page.locator("#newWorkspaceConfirmStartBtn").click();
    await expect(page.locator("#newWorkspaceConfirmOverlay")).toBeHidden();

    // The workspace is now empty -- no Time Group canvas, so nothing left
    // for a stale rAF loop to draw into. Give any (there should be none)
    // still-scheduled animation frame a chance to fire and throw before
    // asserting a clean console.
    await page.waitForTimeout(300);
    await expect(page.locator("#wwTimeGroupCanvases .ww-time-group-canvas")).toHaveCount(0);
    expect(consoleErrors, `Unexpected console/page errors:\n${consoleErrors.join("\n")}`).toEqual([]);
  });
});
